:Author: Mitjas
:Email: {AuthorEmail}
:Date: 15/11/2019
:Revision: version Beta 1.0
:License: MIT License/MyTja License/CC BY-SA 4.0

= Project: PowerOS

OS for powerbanks

== Step 1: Installation
Upload all the code to Arduino and you are all done!

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

No assembely diagram

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 PowerOS                => Arduino sketch folder
  ├── PowerOS.ino       => main Arduino file
  ├── PowerLib.h        => lib with all pictures in Hex
  ├── PowerOS.h         => lib with main parts
  └── ReadMe.adoc       => this file
....

=== License
This project is released under a CC BY-SA 4.0 License.

=== Contributing
To contribute to this project please contact Mitjas https://id.arduino.cc/Mitjas

=== BOM
Bill of Materials!
This are minimum of materials that you need.
Arduino can be used with every gen. that is better than 328p, including 328p

|===
| ID | Part name                  |Part number| Quantity
| O1 | OLED 0.96" yellow-blue     | OLED-1    | 1
| L1 | Buttons                    | BTN-111   | 4
| A1 | Min. Arduino Pro Mini      | ARD-NpmU  | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
